POST http://localhost:8080/feed/1/comment
Content-Type: application/json

{
  "userId": 33,
  "text": "Wow Its odl one!"
}

###
GET http://localhost:8080/feed/1/comment

###

DELETE http://localhost:8080/feed/1/comment/1

###

PUT http://localhost:8080/feed/1/comment
Content-Type: application/json

{
  "id": 34,
  "text": "다시마 맛있어!"
}


###

GET http://localhost:8080/feed?pageNo=0&pageSize=5



###

PUT http://localhost:8080/feed/1/like?userId=38

###

GET http://localhost:8080/feed/1?userId=38

###
PUT http://localhost:8080/feed/1/Share?userId=33

###
