POST http://localhost:8080/feed/1/comment/
Content-Type: application/json

{
  "userId": 33,
  "text": "Wow Its odl one!"
}

###

DELETE http://localhost:8080/Comment/delete?Id=33

###

GET http://localhost:8080/Comment/34

###

GET http://localhost:8080/Comment/count/32

###

GET http://localhost:8080/feed/

###

GET http://localhost:8080/init

###

PUT http://localhost:8080/feed/1/like?userId=38

###

GET http://localhost:8080/feed/1?userId=38

###
PUT http://localhost:8080/feed/1/Share?userId=33

###
